INSERT INTO users (username,password) VALUES ('Caleb','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm'); /*password is pass*/
INSERT INTO users (username,password) VALUES ('Jake','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Tom','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Mitch','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Trish','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Roderigo','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Johndoe','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('James','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Theo','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Nick','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Justin','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Ryan','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Ella','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Emma','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Kate','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Chris','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Alex','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Jordan','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Sam','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Max','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Logan','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Hannah','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Josh','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Will','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Homer','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Bart','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Lisa','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Maggie','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Marge','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Larry','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Caden','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Ally','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Dalton','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Grace','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Emily','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Morgan','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');
INSERT INTO users (username,password) VALUES ('Andrew','$2a$12$nmc04NyhuWQsIuvmbw2mAuQiuyArhSNDwwUET/hloBZ2JaNcxnuQm');

INSERT INTO facilities (name, location) VALUES ('CU Rec Center', '80302');
INSERT INTO facilities (name, location) VALUES ('Rocky Mountain Tennis Center', '80302');
INSERT INTO facilities (name, location) VALUES ('Knollwood Tennis Courts', '80302');
INSERT INTO facilities (name, location) VALUES ('Meadows Club', '80303');
INSERT INTO facilities (name, location) VALUES ('South Campus Tennis Complex', '80305');
INSERT INTO facilities (name, location) VALUES ('Fairview High School Tennis Courts', '80305');
INSERT INTO facilities (name, location) VALUES ('Martin Park', '80305');
INSERT INTO facilities (name, location) VALUES ('Denver Tennis Club', '80220');
INSERT INTO facilities (name, location) VALUES ('JCC Tennis Center', '80246');
INSERT INTO facilities (name, location) VALUES ('Pulaski Park', '80209');
INSERT INTO facilities (name, location) VALUES ('Denver Tennis League', '80205');
INSERT INTO facilities (name, location) VALUES ('City Park', '80205');
INSERT INTO facilities (name, location) VALUES ('Smiley MS', '80207');
INSERT INTO facilities (name, location) VALUES ('Rocky Mountain Lake Tennis Courts', '80221');
INSERT INTO facilities (name, location) VALUES ('Sloans Lake', '80212');
INSERT INTO facilities (name, location) VALUES ('Meadow Creek', '80214');
INSERT INTO facilities (name, location) VALUES ('La Alma Tennis Courts', '80204');
INSERT INTO facilities (name, location) VALUES ('Randy Ross Tennis Center', '80112');
INSERT INTO facilities (name, location) VALUES ('Rusty Sun', '80112');
INSERT INTO facilities (name, location) VALUES ('Life Time Tennis', '80122');
INSERT INTO facilities (name, location) VALUES ('Jamison Tennis Courts', '80112');
INSERT INTO facilities (name, location) VALUES ('Cook Creek Tennis Courts', '80124');
INSERT INTO facilities (name, location) VALUES ('Walnut Hills Tennis Courts', '80112');
INSERT INTO facilities (name, location) VALUES ('Club Greenwood', '80111');
INSERT INTO facilities (name, location) VALUES ('Sundance Hills', '80111');
INSERT INTO facilities (name, location) VALUES ('Arapahoe Tennis Club', '80113');
INSERT INTO facilities (name, location) VALUES ('Holly Park', '80111');
INSERT INTO facilities (name, location) VALUES ('Eastmoor Swim & Tennis Club', '80237');
INSERT INTO facilities (name, location) VALUES ('Rosamond Park', '80237');
INSERT INTO facilities (name, location) VALUES ('Southridge Tennis Courts', '80130');
INSERT INTO facilities (name, location) VALUES ('Bonforte Park', '80907');
INSERT INTO facilities (name, location) VALUES ('Colorado Springs Racquet Club', '80915');
INSERT INTO facilities (name, location) VALUES ('Cheyenne Mountain Country Club', '80906');
INSERT INTO facilities (name, location) VALUES ('Pikes Peak Athletics', '80906');
INSERT INTO facilities (name, location) VALUES ('Burghart Tennis Courts', '80903');
INSERT INTO facilities (name, location) VALUES ('Foothills Swim & Racquet Club', '80919');
INSERT INTO facilities (name, location) VALUES ('Sandstone Park', '80922');
INSERT INTO facilities (name, location) VALUES ('Banning Lewis Ranch', '80927');
INSERT INTO facilities (name, location) VALUES ('John Venizia Community Park', '80920');
INSERT INTO facilities (name, location) VALUES ('Black Forest Park', '80908');
INSERT INTO facilities (name, location) VALUES ('Cottonwood Creek', '80918');
